import { GasChannel, RelayItem } from '../types/medgas';
import { DEFAULT_THRESHOLDS } from './units';

export const DEFAULT_GAS_CHANNELS: GasChannel[] = [
  {
    id: 'gas-o2',
    code: 'O2',
    nameEn: 'Medical Oxygen',
    nameTh: 'ออกซิเจนทางการแพทย์',
    color: '#10b981', // Medical green
    currentValue: 4.12,
    displayValue: 4.12,
    unit: 'bar',
    status: 'NORMAL',
    threshold: DEFAULT_THRESHOLDS.O2,
    bankSource: 'LEFT',
    flowRateLpm: 38.5,
    temperatureC: 23.4,
  },
  {
    id: 'gas-ma4',
    code: 'MA4',
    nameEn: 'Medical Air 4 bar',
    nameTh: 'อากาศทางการแพทย์ 4 บาร์',
    color: '#38bdf8', // Light blue/cyan
    currentValue: 4.05,
    displayValue: 4.05,
    unit: 'bar',
    status: 'NORMAL',
    threshold: DEFAULT_THRESHOLDS.MA4,
    bankSource: 'LEFT',
    flowRateLpm: 64.2,
    temperatureC: 22.8,
  },
  {
    id: 'gas-sa7',
    code: 'SA7',
    nameEn: 'Surgical Air 7 bar',
    nameTh: 'อากาศขับเครื่องมือผ่าตัด 7 บาร์',
    color: '#6366f1', // Indigo
    currentValue: 7.08,
    displayValue: 7.08,
    unit: 'bar',
    status: 'NORMAL',
    threshold: DEFAULT_THRESHOLDS.SA7,
    bankSource: 'LEFT',
    flowRateLpm: 18.0,
    temperatureC: 23.1,
  },
  {
    id: 'gas-vac',
    code: 'VAC',
    nameEn: 'Medical Vacuum',
    nameTh: 'สุญญากาศทางการแพทย์',
    color: '#eab308', // Amber / Medical Vacuum Yellow
    currentValue: -66.4,
    displayValue: -66.4,
    unit: 'kPa',
    status: 'NORMAL',
    threshold: DEFAULT_THRESHOLDS.VAC,
    bankSource: 'LEFT',
    flowRateLpm: 120.5,
    temperatureC: 25.2,
  },
  {
    id: 'gas-n2o',
    code: 'N2O',
    nameEn: 'Nitrous Oxide',
    nameTh: 'ก๊าซไนตรัสออกไซด์ (ดมสลบ)',
    color: '#3b82f6', // Medical Blue
    currentValue: 4.02,
    displayValue: 4.02,
    unit: 'bar',
    status: 'NORMAL',
    threshold: DEFAULT_THRESHOLDS.N2O,
    bankSource: 'LEFT',
    flowRateLpm: 4.2,
    temperatureC: 21.9,
  },
  {
    id: 'gas-co2',
    code: 'CO2',
    nameEn: 'Carbon Dioxide',
    nameTh: 'ก๊าซคาร์บอนไดออกไซด์ (ส่องกล้อง)',
    color: '#94a3b8', // Slate / Gray
    currentValue: 4.08,
    displayValue: 4.08,
    unit: 'bar',
    status: 'NORMAL',
    threshold: DEFAULT_THRESHOLDS.CO2,
    bankSource: 'LEFT',
    flowRateLpm: 7.5,
    temperatureC: 22.1,
  },
];

export const DEFAULT_RELAYS: RelayItem[] = [
  {
    id: 1,
    pin: 0,
    name: 'Y1',
    labelEn: 'Left Bank Solenoid',
    labelTh: 'โซลินอยด์วาล์วถังชุดซ้าย',
    description: 'Manifold Left Cylinder Bank Valve (GPIO0)',
    state: false,
  },
  {
    id: 2,
    pin: 1,
    name: 'Y2',
    labelEn: 'Right Bank Solenoid',
    labelTh: 'โซลินอยด์วาล์วถังชุดขวา',
    description: 'Manifold Right Cylinder Bank Valve (GPIO1)',
    state: false,
  },
  {
    id: 3,
    pin: 2,
    name: 'Y3',
    labelEn: 'Main Supply Line (R3)',
    labelTh: 'วาล์วจ่ายท่อหลัก (R3 เริ่มต้น ON)',
    description: 'Primary Hospital Supply Distribution Header (GPIO2)',
    state: true, // v3.1.0 boot default
    defaultOn: true,
  },
  {
    id: 4,
    pin: 3,
    name: 'Y4',
    labelEn: 'Audio Alarm & Strobe',
    labelTh: 'ไซเรนเสียงและสัญญาณไฟเตือนภัย',
    description: 'Medical Gas Master Alarm Horn / Flasher (GPIO3)',
    state: false,
  },
  {
    id: 5,
    pin: 4,
    name: 'Y5',
    labelEn: 'Ventilation Fan',
    labelTh: 'พัดลมระบายอากาศห้องก๊าซ',
    description: 'Gas Manifold Room Safety Exhaust Fan (GPIO4)',
    state: false,
  },
  {
    id: 6,
    pin: 10,
    name: 'Y6',
    labelEn: 'Nurse Station Beacon',
    labelTh: 'ไฟสัญญาณเตือนเคาน์เตอร์พยาบาล',
    description: 'Remote ICU / OR Station Alarm Contact (GPIO10)',
    state: false,
  },
];
